name = "spotify-badge-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Environment variables (set these using wrangler secret put)
# SPOTIFY_CLIENT_ID
# SPOTIFY_CLIENT_SECRET  
# SPOTIFY_REFRESH_TOKEN

# Custom domain configuration (optional)
# Uncomment and update with your subdomain
# routes = [
#   { pattern = "spotify.yourdomain.com/*", custom_domain = true }
# ]

[env.production]
name = "spotify-badge-api"

[env.development]
name = "spotify-badge-api-dev"