name = "spotify-badge-api"
main = "src/index.js"
compatibility_date = "2025-08-16"

# Environment variables (set these using wrangler secret put)
# SPOTIFY_CLIENT_ID
# SPOTIFY_CLIENT_SECRET  
# SPOTIFY_REFRESH_TOKEN

[env.production]
name = "spotify-badge-api"

[env.development]
name = "spotify-badge-api-dev"

[observability.logs]
enabled = true